apiVersion: v1
kind: Pod
metadata:
  name: test-pod-success
  namespace: dev-namespace
spec:
  containers:
    - name: cal-app
      image: 501170964283.dkr.ecr.ap-south-1.amazonaws.com/cal-app
      resources:
        requests:
          cpu: "0.5" # Within the allowed limit
          memory: "512Mi" # Within the allowed limit
        limits:
          cpu: "1" # Allowed max CPU
          memory: "1Gi" # Allowed max memory