apiVersion: v1
kind: Pod
metadata:
  name: cal-pod
  labels:
    app: cal-app
spec:
  containers:
    - name: cal-container
      image: 396608804965.dkr.ecr.ap-south-1.amazonaws.com/cal-app
      ports:
        - containerPort: 80