apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: cal-rs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cal-app
  template:
    metadata:
      labels:
        app: cal-app
    spec:
      containers:
        - name: cal-container
          image: 396608804965.dkr.ecr.ap-south-1.amazonaws.com/cal-app
          ports:
            - containerPort: 80
    